sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_d4fd0618c9ee_key -iv $encrypted_d4fd0618c9ee_iv -in multi-k8s-281317-7a59a943e961.json.enc -out multi-k8s-281317-7a59a943e961.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json