sudo: required
services:
  - docker

before_install:
  - docker build -t shaggydog/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run shaggydog/react-test npm test -- --coverage

after_success:
  - docker build -t shaggydog/multi-client ./client
  - docker build -t shaggydog/multi-nginx ./nginx
  - docker build -t shaggydog/multi-server ./server
  - docker build -t shaggydog/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push shaggydog/multi-client
  - docker push shaggydog/multi-nginx
  - docker push shaggydog/multi-server
  - docker push shaggydog/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env-1
  bucket_name: elasticbeanstalk-us-east-2-887293043336

  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY