apiVersion: certmanager.k8s.io/v1alpha2
kind: certificate
metadata:
  name: shaggydog-me-tls
spec:
  secretName: shaggydog-me
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: shaggydog.me
  dnsNames:
    - shaggydog.me
    - www.shaggydog.me
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - shaggydog.me
          - www.shaggydog.me