version: '3'
services:
  redis:
    image: 'redis:latest'
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379